### ISSUE TITLE
Build my own geph-exit linux server

### ISSUE THREAD

**Issue by DavidLeeberman** [geph-official/geph4-client#10]
Hello,

Is there a way to build a dedicated single-hop geph-exit linux server on geph4 like there was on geph2? Or is there a way to get the binaries for the latest geph-exit and geph-client respectively?

Thank you!

**Comment by showgood163** [comment]
The self-hosting guide (WIP) is here

https://github.com/geph-official/geph4/wiki/Self-hosting-guide-(WIP)
