### ISSUE TITLE
Self-hosted exit option in Geph client

### ISSUE THREAD

**Issue by amirsaam** [geph-official/geph4-client#103]
Hi,

I'm asking to add an option in Geph clients (all of them even iOS beta) to use self-hosted server information as exit server cause there is no client other than Geph itself than can handle it's own connections so there is no good explanation to not have this option in the clients while the cargo release has the override functionality!

It should be side-to-side, I should be able to use my own self-hosted exit in Geph client + having Geph own servers available to use.

I'll appreciate any help cause currently free internet access in our country is a dream.
Thanks

**Comment by samuraee** [comment]
+1
in order to use my **self-hosted** server
```
geph4-client connect --override-connect <PUBLIC_KEY>@<IP_ADDRESS>:PORT 
```
**NOT** works!!!
