### ISSUE TITLE
Linux版如何使用

### ISSUE THREAD

**Issue by yqs6666** [geph-official/geph4-client#107]
geph4-client-4.7.10
geph4-client-4.7.10.tar.gz
Geph-x86_64.flatpak
现在有这三个文件，flatpak不知如何安装，github下载的压缩包解压之后也不知道如何运行，把所有.sh都试了一遍也不行55555

**Comment by Luv-Ray** [comment]
下载好的文件所在目录下：`flatpack install Geph-x86_64.flatpak`

**Comment by CodePrometheus** [comment]
> 下载好的文件所在目录下：`flatpack install Geph-x86_64.flatpak`

But I ran into something like this “Invalid checksum of length 2043 expected 32”

**Comment by lyonxh** [comment]
> 下载好的文件所在目录下：`flatpack install Geph-x86_64.flatpak`

装好启动 白屏 and error

**Comment by CusterFun** [comment]
Geph-x86_64.flatpak 这个文件从哪里下载呀，官网只有 linux-amd64 的呢
