### ISSUE TITLE
点击连接没有反应

### ISSUE THREAD

**Issue by counthlk1** [geph-official/geph4-client#112]
![截图 2023-03-29 18-42-08](https://user-images.githubusercontent.com/129283044/228519695-964441a6-1e60-4e77-b722-e764bd1a6f4d.png)
UBUNTU系统，只是按钮变颜色而已，并没有连接，而且接下来连墙内网站也无法访问了。
另外，geph能看日志吗？

**Comment by realFlyjack** [comment]
同问

**Comment by AnyWAT** [comment]
4.7.12特质，用户界面与内核已失联，如PC结束已在运行的内核进程，再启动即可。

**Comment by bl-sun** [comment]
> 4.7.12特质，用户界面与内核已失联，如PC结束已在运行的内核进程，再启动即可。

内核进程是啥名？

**Comment by AnyWAT** [comment]
geph4-client

**Comment by bl-sun** [comment]
> geph4-client

windows上好像没有这个进程。今天又遇到了，重启了几次电脑才解决问题。不知道具体原因是什么。总觉得是我自己关电脑之前忘记关闭迷雾通了
