### ISSUE TITLE
ubuntu安装.flatpak超级慢，能不能提供以前那种tar.xz压缩包

### ISSUE THREAD

**Issue by JungleKofa** [geph-official/geph4-client#113]
感觉没有以前解压压缩包方便

#### 安装flatpak
sudo apt install flatpak
#### 安装软件应用插件
sudo apt install gnome-software-plugin-flatpak
#### 双击文件安装或者命令行安装
flatpak install Geph-x86_64.flatpak

之后开始安装要等很久，安装速度也非常慢
Required runtime for io.geph.GephGui/x86_64/master (runtime/org.gnome.Platform/x86_64/41) found in remote flathub-1
Do you want to install it? [Y/n]: y
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.

io.geph.GephGui permissions:
    ipc       network              wayland              x11
    dri       file access [1]      dbus access [2]

    [1] host
    [2] ca.desrt.dconf, org.freedesktop.Flatpak

        ID                                  Branch Op Remote          Download
 1. [|] org.freedesktop.Platform.GL.default 21.08  i  flathub-1       < 129.8 MB
 2. [ ] org.freedesktop.Platform.openh264   2.0    i  flathub-1         < 1.5 MB
 3. [ ] org.gnome.Platform.Locale           41     i  flathub-1       < 337.1 MB (partial)
 4. [ ] org.gtk.Gtk3theme.Yaru              3.22   i  flathub-1       < 191.5 kB
 5. [ ] org.gnome.Platform                  41     i  flathub-1       < 292.7 MB
 6. [ ] io.geph.GephGui                     master i  gephgui5-origin 0 bytes

Installing 1/6…

**Comment by nullchinchilla** [comment]
这是因为需要下载dependencies。之后覆盖新版本的话，会非常快，并不需要重新安装这些步骤。这样平均下来会更快
