### ISSUE TITLE
如何处理 VPN mode requires admin privileges on Windows!!!

### ISSUE THREAD

**Issue by Neph0s** [geph-official/geph4-client#117]
我有2个vpn在使用，前段时间迷雾通连不上，就用了clash for windows。
用完之后，我在迷雾通里，想开全局代理，就会显示：
cannot start daemon

Caused by:
    VPN mode requires admin privileges on Windows!!! 

一个解决方法是我用管理员权限打开迷雾通，但这似乎有很大的问题，会使我的微信和校园网vpn都失效。

也就是说，我要么无法使用全局代理，要么使用全局代理时无法使用微信和校园网vpn

请问应该如何解决？

**Comment by nullchinchilla** [comment]
全局代理=强制所有程序使用迷雾通，从根本上来说是和其它vpn，或不代理某些程序不兼容的。如果需要又全局又分流，建议使用第三方软件配合迷雾通的默认socks模式。
