### ISSUE TITLE
linux 启动白屏 下面是报错

### ISSUE THREAD

**Issue by lyonxh** [geph-official/geph4-client#118]
(WebKitWebProcess:34): Gdk-WARNING **: 15:11:24.168: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was '167'.
  (Details: serial 179 error_code 167 request_code 151 (unknown) minor_code 21)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by nullchinchilla** [comment]
能发一下你的系统信息吗？我无法重现。

**Comment by Jyanr** [comment]
同样的问题，arch linux kde

**Comment by lyonxh** [comment]
Linux version 4.19.0-amd64-desktop (jinxiaobo@x86-compile-PC) (gcc version 8.3.0 (Uos 8.3.0.5-1+dde)) #5000 SMP Tue Oct 12 10:59:29 CST 2021

**Comment by Jyanr** [comment]
更新
我解决了，是下载有问题，我把flatpak镜像换了重下就好了
https://zh.fedoracommunity.org/2020/05/13/try-on-flatpak-mainland-china-mirror.html

**Comment by Jyanr** [comment]
更新
我解决了，单纯的flatpak依赖下载问题

**Comment by lyonxh** [comment]
ok
