### ISSUE TITLE
4.8.1 升级后 window11 一直再刷新用户信息

### ISSUE THREAD

**Issue by wynshiter** [geph-official/geph4-client#120]
4.8.1 升级后 window11 一直再刷新用户信息

**Comment by AnyWAT** [comment]
新建了某个用户文件夹。。。
也许——
退出迷雾通，其安装目录下的 MicrosoftEdgeWebview2Setup.exe 更新一下 WebView 或许就好了

**Comment by AnyWAT** [comment]
或者：
https://community.geph.io/t/topic/11582/2

**Comment by wynshiter** [comment]
好的，已解决
