### ISSUE TITLE
geph stucks on "refreshing user info"

### ISSUE THREAD

**Issue by paymanz** [geph-official/geph4-client#121]
Updated geph 4.8.1 on windows 10 yesterday and since then it keeps showing a message "refreshing user info". 

Should i rollback to previous version or its a server side problem?!

**Comment by AnyWAT** [comment]
try:
close the app
run MicrosoftEdgeWebview2Setup.exe to update WebView
run the app again

![image](https://user-images.githubusercontent.com/37962734/236628948-f96e863d-a70a-4ad2-b382-abda8556b845.png)

**Comment by AnyWAT** [comment]
try:
close the app
run MicrosoftEdgeWebview2Setup.exe to update WebView
run the app again

![image](https://user-images.githubusercontent.com/37962734/236628948-f96e863d-a70a-4ad2-b382-abda8556b845.png)

**Comment by AnyWAT** [comment]
OR：
https://community.geph.io/t/topic/11582/2

**Comment by paymanz** [comment]
updating edge didnt work. downgraded to 4.7 for now.
