### ISSUE TITLE
新版本问题

### ISSUE THREAD

**Issue by jiujianxiaotian** [geph-official/geph4-client#124]
[连接服务器后无法访问Facebook且服务器无数据流量。

![问题](https://user-images.githubusercontent.com/132053165/237027275-dfb37b20-0d8c-4a46-99af-3b8d8d47a3c8.jpg)

**Comment by AnyWAT** [comment]
描述的问题：啥系统？

**Comment by AnyWAT** [comment]
排除代理设置错误，PC上登录999%服务器就是如此。试试更改位置。

**Comment by jiujianxiaotian** [comment]
> 描述的问题：啥系统？

Windows11，按照你在别的帖子上的建议设置了LAN地址后解决。多谢

**Comment by jiujianxiaotian** [comment]
> 不过，貌似最佳方案是： https://community.geph.io/t/topic/10773/6?u=anywat

收藏了，谢谢。已解决
