### ISSUE TITLE
Please update Self hosting guide in WiKi

### ISSUE THREAD

**Issue by TweakiOS** [geph-official/geph4-client#129]
Current guide is out of date obviously. Thanks.
geph4-client add one more SUBCOMMANDS:
    auth-keypair
    auth-password
    help

**Comment by amirshabanics** [comment]
also i use the guide and run a server with geph-exit but I can connect to it with this command:
`geph4-client connect --override-connect publickey@ip:port`

every time I ran this command it send me the help text

**Comment by sadministrator** [comment]
This issue has been fixed and will be released in version 4.9.2.
