### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by nemoiwkryang** [geph-official/geph4-client#130]
版本4.8.5，登录时显示"unknown variant `xxxxxxxx`, expected `Password` or `Signature`", line: 0, column: 0
xxxxxxx是用户名称

**Comment by AnyWAT** [comment]
用回旧版？https://f001.backblazeb2.com/file/geph4-dl/geph-releases/windows-stable/4.8.2/geph-windows-setup.exe

**Comment by leisurelicht** [comment]
> 错误 Error("unknown variant `yuf19.2022@gmail.com`, expected `Password` or `Signature`", line: 0, column: 0) OK
> 
> 怪我手贱，本来是登录的还能用，我看到这个错误，就不舒服，试试退出重新登录，现在好了，压根没法登录

同款手欠

**Comment by leisurelicht** [comment]
mac可用旧版本： https://f001.backblazeb2.com/file/geph4-dl/geph-releases/macos-stable/4.8.4/geph-macos.dmg

**Comment by nemoiwkryang** [comment]
旧版看上去可以正常使用，不知道是不是新版本的bug，看后续修复吧
