### ISSUE TITLE
Geph error on login

### ISSUE THREAD

**Issue by sinamcr7** [geph-official/geph4-client#131]
hi my geph vpn got this error and I tried to relogin to fix it but it shows error over and over again event with reinstall
Error("unknown variant 'username', expected 'Password' or 'Signature'", line 0, column:0)
I couldn't find anything about this error anywhere please help me fix it

**Comment by JungleKofa** [comment]
Return to old version

**Comment by sinamcr7** [comment]
where can I find old version for windows? couldn't find any exe file for windows in github or app website

**Comment by AnyWAT** [comment]
https://github.com/geph-official/geph4-client/issues/130#issuecomment-1565892111

**Comment by thisbefruit** [comment]
Hi! This issue has been fixed in the newest version. You can upgrade to the newest version from our website: geph.io
