### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by child0622** [geph-official/geph4-client#132]
新版连接上之后还是无法正常浏览网站，脸书和油管这些都无反应，还有为什么全局vpn打不开，win10系统

**Comment by AnyWAT** [comment]
如是说：
代理——规则或全局，都不能正常浏览网站。
不会是节点与
设置——Clash 内核  之间不匹配？试试更换内核。

**Comment by child0622** [comment]
> 
如何更换 我是新手

**Comment by AnyWAT** [comment]
> 全局vpn打不开，win10系统

貌似（每次）得以管理员身份运行迷雾通。
个人不建议使用VPN，如带宽至少100M 对接免费迷雾通 1M？

> 新版连接上之后还是无法正常浏览网站，脸书和油管这些都无反应

禁用浏览器代理插件或使用系统代理，迷雾通（默认）开启“自动配置代理”。
貌似最佳：关闭“自动配置代理”，浏览器用代理插件，其它应用在其内部设置代理。
