### ISSUE TITLE
Unsupported 16-bit Application Error

### ISSUE THREAD

**Issue by l3est** [geph-official/geph4-client#133]
I'm getting this error on windows 11 pro on v4.8.6 (4.8.5 was working fine)
![image](https://github.com/geph-official/geph4-client/assets/8002505/d89d4158-b05b-40fe-af83-e27e78ec441f)

**Comment by jefftsai2050** [comment]
it 4.8.6 can not be started on windows 11

**Comment by AnyWAT** [comment]
https://community.geph.io/t/topic/12351/8?u=anywat

**Comment by l3est** [comment]
fixed in 4.8.7
