### ISSUE TITLE
新版加入的黑框代码界面感觉比以前耗电多了

### ISSUE THREAD

**Issue by dgfrwx** [geph-official/geph4-client#134]
建议删除掉吧，小白也不知道用来干什么

**Comment by AnyWAT** [comment]
用户界面停留在日志页面，暂停每10分钟一次的服务器列表 summary.json 更新及 melprot 文件夹下同步文件的生成。
不知是否对手机有效：https://community.geph.io/t/topic/12312/4?u=anywat

**Comment by dgfrwx** [comment]
不知道操作啊？只是希望作者在安卓版删除这个黑框代码界面，毕竟手机电量宝贵啊，win版继续保留啊，反正电脑不用管电量消耗

**Comment by AnyWAT** [comment]
> 用户界面停留在日志页面

不是有连接的首页，是有流量、延迟、日志的那页

**Comment by dgfrwx** [comment]
> > 用户界面停留在日志页面
> 
> 不是有连接的首页，是有流量、延迟、日志的那页

对啊，就是那页怎么删除那页？挺耗电的

**Comment by AnyWAT** [comment]
### 停留
