### ISSUE TITLE
macOS无法运行4.8.7版本

### ISSUE THREAD

**Issue by Andy-Yanhui** [geph-official/geph4-client#135]
从4.8.6更新4.8.7后，现在客户端一直无法连接使用Log如附件。
[Log下载](https://community.geph.io/uploads/short-url/8zaj7X1M0qmVv52KugaUNC7n8uC.zip)
@nullchinchilla Tung
#macOS客户端无法使用

**Comment by AnyWAT** [comment]
已断开但连接按钮暗色，疑似。。。
https://community.geph.io/t/topic/11858/3?u=anywat

**Comment by Andy-Yanhui** [comment]
原因：“正在刷新用户信息”与“geph4-client”进程有干涉，导致的
临时解决方案：在活动监视器中强制退出“geph4-client”进程之后重启App
Ps：以上对策如再次点击刷新按钮后，还需上述操作

**Comment by AnyWAT** [comment]
提出问题的第一人：https://community.geph.io/t/topic/10945
（4.7.12开始，已正常代理的情况下，启动迷雾通，显示已断开）点击连接，（按钮变暗）没有反应，但其实已经连接了。现在根本无法断开连接了，即使强制退出，Geph的进程仍在！因为强制退出只能杀死GUI，而不能杀死client！:disappointed:
Windows 下的完美再现：正常运行的迷雾通窗口显示在桌面——在任务管理器内结束 gephgui-wry.exe 进程，窗口消失——再次启动迷雾通，显示已断开。。。点击连接，（按钮变暗）没有反应，但其实已经连接了。
4.7.10及以前：
1、启动迷雾通，如显示已连接，说明已有 geph4-client.exe 进程在运行，并且代理正常。
2、完全正常的启动，显示已断开，说明没有 geph4-client.exe 进程在运行。

**Comment by Andy-Yanhui** [comment]
macOS 迷雾通 客户端：只要打开了迷雾通，geph4-client.exe 进程就会启动的

**Comment by Andy-Yanhui** [comment]
Close
