### ISSUE TITLE
根本连不上 都是拒绝连接 我是linux版 链接中一直在转

### ISSUE THREAD

**Issue by lyonxh** [geph-official/geph4-client#138]

**Comment by AnyWAT** [comment]
Windows 系统上采用的是 WebView 框架，运行迷雾通安装文件夹下的 MicrosoftEdgeWebview2Setup.exe 或可解决问题；
貌似 Mac 也相似，linux 呢？

**Comment by AnyWAT** [comment]
不会是24小时内账户登入（登出）达到了10次的上限？
