### ISSUE TITLE
为付费用户提供密码找回功能

### ISSUE THREAD

**Issue by lifejx** [geph-official/geph4-client#143]
我是付费用户，退出够无法登录，提示无效用户或密码，原来密码不好使了，我只知道用户名，不是邮箱地址作为用户名，不知如何找回密码

**Comment by AnyWAT** [comment]
https://community.geph.io/t/topic/12315

**Comment by jackiej70** [comment]
我是付费用户，退出够无法登录，提示无效用户或密码，原来密码不好使了，我只知道用户名，不是邮箱地址作为用户名，不知如何找回密码

**Comment by jackiej70** [comment]
不知道 谁能帮助我

**Comment by AnyWATgh** [comment]
近期版本已不再用账户、密码，改用账户密钥。
Win下如果成功运行过图形模式，C:\Users\用户名\AppData\Local\Temp\ .tmp*.yaml 文件内有账户密钥。

**Comment by jackiej70** [comment]
我不是很明白你的意思， 能详细说明吗？ 谢谢
________________________________
发件人: AnyWATgh ***@***.***>
发送时间: 2026年1月20日 15:43
收件人: geph-official/geph4-client ***@***.***>
抄送: jackiej70 ***@***.***>; Comment ***@***.***>
主题: Re: [geph-official/geph4-client] 为付费用户提供密码找回功能 (Issue #143)

[https://avatars.githubusercontent.com/u/229039490?s=20&v=4]AnyWATgh left a comment (geph-official/geph4-client#143)<https://github.com/geph-official/geph4-client/issues/143#issuecomment-3771474767>

Win下如果成功运行过图形模式，C:\Users\用户名\AppData\Local\Temp\ .tmp*.yaml 文件内有账户密钥。

―
