### ISSUE TITLE
点连接无反应

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [geph-official/geph4-client#147]
电脑:win10
迷雾通v4.9.1

选一个服务器，点连接后无反应，按钮会变一下色，但又变回，不会进行边接。

我试了4.8也是一样的。

**Comment by AnyWAT** [comment]
此刻正常呢。
莫非系统有国产杀毒、卫士、管家之流？

**Comment by piiiiiiiiiiiiiii** [comment]
> 此刻正常呢。 莫非系统有国产杀毒、卫士、管家之流？

火绒

**Comment by piiiiiiiiiiiiiii** [comment]
现在电脑上没有任何杀软卫士之类的，重新安装geph还是一样的，点击连接按钮变成灰色，实际上没有连接。

**Comment by AnyWAT** [comment]
退出迷雾通，任务管理器内检查、终止 geph4-client.exe 进程，再以管理员身份运行一下？

**Comment by piiiiiiiiiiiiiii** [comment]
![image](https://github.com/geph-official/geph4-client/assets/12248166/2bf9a679-fff5-46cb-9610-235989f81993)

找不到geph4-client.exe  @AnyWAT

**Comment by AnyWAT** [comment]
![image](https://github.com/geph-official/geph4-client/assets/37962734/83b9ad98-9d99-4e77-aeeb-9a26880c12a4)

**Comment by piiiiiiiiiiiiiii** [comment]
> ![image](https://user-images.githubusercontent.com/37962734/269851294-83b9ad98-9d99-4e77-aeeb-9a26880c12a4.png)

没用，我重装过好几个geph版本，就差重装win10了

**Comment by AnyWAT** [comment]
没有火绒的Win10，迷雾通服务（器）正常就运行正常。

**Comment by piiiiiiiiiiiiiii** [comment]
> 没有火绒的Win10，迷雾通服务（器）正常就运行正常。
> 
> 如果仍没解决，检查系统组件的完整性并修复：https://answers.microsoft.com/zh-hans/windows/forum/all/%E8%BD%AF%E4%BB%B6%E8%BF%90%E8%A1%8C%E4%B8%AD/7d0d0e86-a00d-4077-ae53-a017c67e1aa5
> 
> Autoruns 检查系统的开机启动、服务。。。

geph有开机启动项，或者说后台服务是哪个?

**Comment by AnyWAT** [comment]
前面说的是其它可能的可疑项。
没用过它开机启动，貌似没有服务。

**Comment by AnyWAT** [comment]
试试：
记住账户与密码，退出迷雾通，改名文件夹（万一问题更多，可以返回）
C:\Users\用户名\AppData\Roaming\EBWebView
C:\Users\用户名\AppData\Roaming\geph4-credentials
然后再启动。。。
倘若正常了，则可删除前述二文件夹。

**Comment by piiiiiiiiiiiiiii** [comment]
> 试试： 记住账户与密码，退出迷雾通，改名文件夹（万一问题更多，可以返回） C:\Users\用户名\AppData\Roaming\EBWebView C:\Users\用户名\AppData\Roaming\geph4-credentials 然后再启动。。。 倘若正常了，则可删除前述二文件夹。

故障依旧，我只能归因是操作系统问题了。
不试了，谢谢
