### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by chromer030** [geph-official/geph4-client#149]
Please compile and release the tool on Github Release (via Github Actions) and save people from compiling on every version, there are existing issues requesting binary files: https://github.com/geph-official/geph4-client/issues/144 https://github.com/geph-official/geph4-client/issues/141
Thanks.

**Comment by nullchinchilla** [comment]
If you look at the CircleCI files, we already release versions through CircleCI.

Where the binaries are placed is undocumented, but currently it is 

```
https://f001.backblazeb2.com/file/geph-dl/geph4-binaries/v4.9.8/geph4-client-linux-amd64
```

etc
