### ISSUE TITLE
很奇怪4.8.9版本会调用lav视频解码器，导致lav崩溃

### ISSUE THREAD

**Issue by Index-LibrorumProhibitorum** [geph-official/geph4-client#154]
昨天晚上突然出现的问题，无缘无故风扇狂转，开任务管理器才发现LAV解码器占用爆了，这个解码器是配pot用的，点了下缩略栏里面的迷雾通图标，任务管理器里面的lav就没了。
当时只开了个迷雾通只代理浏览器和比特彗星正在上传。

想换旧版本，却根本没有下载，谁有4.7版本？ 
![IMG_20231008_195303](https://github.com/geph-official/geph4-client/assets/105000340/c33307dd-9011-4bd1-b239-06a6b2d94912)

**Comment by AnyWAT** [comment]
官网：https://geph.io 
右键复制下载链接，修改版本号即可下载以往旧版。

**Comment by Index-LibrorumProhibitorum** [comment]
> 官网：https://geph.io 右键复制下载链接，修改版本号即可下载以往旧版。

不行呀，试了4.7.0，404

**Comment by AnyWAT** [comment]
> 最早只能4.7.5再早的就不行了

正确，貌似 4.7.X 之前的版本已不再支持。
