### ISSUE TITLE
那个更新版本的弹窗可以关了吗？

### ISSUE THREAD

**Issue by Index-LibrorumProhibitorum** [geph-official/geph4-client#155]
在win10用，之前的版本只是用一次弹一次，后面更新到了4.8.9版本，一共就用了几小时累计弹窗几十次，点了不更新没过多久又弹，十分烦，能不能加个选项关掉他？想更新版本时再更新？

**Comment by AnyWAT** [comment]
貌似 4.9 版本没有更新提示了。

**Comment by Index-LibrorumProhibitorum** [comment]
> 貌似 4.9.1/2 版本没有更新提示了。

这个应该是本来就是最新版不需要更新了吧，等4.9.5出来还是弹

**Comment by nullchinchilla** [comment]
This is now tracked in #158
