### ISSUE TITLE
不开全局模式就打不开 huggingface，希望能够吧 huggingface.co 加入到不需要开全局也能链接的网址列表当中

### ISSUE THREAD

**Issue by void-echo** [geph-official/geph4-client#156]
不开全局模式就打不开 huggingface，希望能够吧 huggingface.co 加入到不需要开全局也能链接的网址列表当中。

huggingface 是目前最大的深度学习模型网址，如果访问不了会有很多不便，开全局访问的话又特别慢。

**Comment by AnyWAT** [comment]
不开全局VPN，关闭影响系统的“自动配置代理”，关闭“排除中国大陆流量”，浏览器采用代理插件，配置能自定义切换规则的情景模式，网站白名单随你
