### ISSUE TITLE
突然不能用了

### ISSUE THREAD

**Issue by qunge5211314** [geph-official/geph4-client#157]
2023年10月13日，打开mac版的客户端，怎么也链接不上，更改位置也不能像以前那样拉出来服务器列表

**Comment by qunge5211314** [comment]
以为是版本更新的问题，更新了版本也不行，重启电脑也不行

**Comment by qunge5211314** [comment]
我的是mac版本的

**Comment by qunge5211314** [comment]
> 2023.10.8 4.9.2 Windows10 更改位置失败，无法连接。 退出迷雾通，删除用户文件夹下的 conninfo.json 后再次启动，更改位置成功，连接正常。

mac版本的修复方式有么

**Comment by AnyWAT** [comment]
木有，即使有但没问题咋整？
请尝试搜索硬盘上的 conninfo.json 文件。。。

**Comment by qunge5211314** [comment]
> 木有，即使有但没问题咋整？ 请尝试搜索硬盘上的 conninfo.json 文件。。。

应该是服务器的问题，现在问题解决了哈，能正常访问了，感谢
