### ISSUE TITLE
4.9.9最新版,如法连接上,已经在两个不同环境的不同电脑上均连接不上了.

### ISSUE THREAD

**Issue by strongasahorse** [geph-official/geph4-client#160]
4.9.9最新版,如法连接上,已经在两个不同环境的不同电脑上均连接不上了.

**Comment by AnyWAT** [comment]
PC 试试：断开，删除文件夹 C:\Users\用户名\AppData\Roaming\geph4-credentials
再次（更改位置并）连接

**Comment by AnyWAT** [comment]
借楼，吼吼

@ovoi233 有变更电脑ip属地的方法吗
迷雾通的全局VPN模式貌似可以满足要求。

@XD41 怎么没有全局加速的了？
1、编辑准备运行的如 2.Xray翻墙.cmd
注释（或删除）掉倒数1-3行，即可运行代理但不启动绑定的浏览器
2、按  2.Xray翻墙.cmd 倒数第二行的代理参数，在自己想运行的浏览器的代理插件中设置一下，即可。

**Comment by qunge5211314** [comment]
我也有这个问题，我什么都没动，周一就能用了，感觉最近服务器不是很稳定

**Comment by KuangSheng34** [comment]
我也是,PC端完全连不上了，安卓端还可以

**Comment by KuangSheng34** [comment]
> PC 试试：断开，删除文件夹 C:\Users\用户名\AppData\Roaming\geph4-credentials 再次（更改位置并）连接 或需退出迷雾通，删除太大的日志 C:\Users\用户名\AppData\Local\geph4-logs.db 文件，再次启动。

两个方法都试了，没用
