### ISSUE TITLE
geph无法工作

### ISSUE THREAD

**Issue by pizeroLOL** [geph-official/geph4-client#17]

**Comment by pizeroLOL** [comment]
![Uploading image.png…]()

**Comment by pizeroLOL** [comment]
![image](https://user-images.githubusercontent.com/71167373/118091538-85557480-b3fd-11eb-8c34-9056dc5e050b.png)

**Comment by SHINNUKA** [comment]
me too

**Comment by Sino1984** [comment]
我也登不上，win端的和安卓端的都是。安卓端显示的是other failure'io error：unexpected end of file'

**Comment by ITSRW** [comment]
Same here! Doesn't feel right about this trouble.

**Comment by Saeidmogadam** [comment]
52620راC185E3R4P1
