### ISSUE TITLE
最新的客户端启动失败

### ISSUE THREAD

**Issue by zhangda3** [geph-official/geph4-client#178]
在我启动了客户端后，连接失败
![screenshot-1716625786981](https://github.com/geph-official/geph4-client/assets/69886153/d6a18c43-3a1a-4842-9f40-f3bba6f753e5)

**Comment by AnyWAT** [comment]
截图太奇妙：看顶部貌似客户端界面，却木有底部。。。
试试：取消勾选默认打开的“自动配置代理”（即使用系统代理）

**Comment by zhangda3** [comment]
OK了，成功启动
