### ISSUE TITLE
About the version scheme

### ISSUE THREAD

**Issue by chenrui333** [geph-official/geph4-client#183]
👋 looks like the most recent release was tagged with 4.99.0, but it really smells like a beta unstable release, any reason why not using 4.12.0 or just 5.0.0? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/183769

**Comment by AnyWAT** [comment]
https://lib.rs/crates/geph4-client/versions

**Comment by chenrui333** [comment]
make sense, thanks!
