### ISSUE TITLE
Download an older version on geph on linux

### ISSUE THREAD

**Issue by BGOPC** [geph-official/geph4-client#185]
Hello, I'm using ubuntu linux, I recently switched to the new 4.99 backend and no server is working, they all connect but can't even google they get stuck, I want to download an older version what should I do, please help I don't wanna lose my internet access

**Comment by AnyWAT** [comment]
[官网](https://geph.io)下载旧版：右键下载对应图标，复制链接地址，在浏览器地址栏粘贴，找到地址中最新的如 /4.99.2/ 更改成需要的如 /4.10.1/ 即可。

**Comment by AnyWAT** [comment]
官网已从V4.99.2更新到V4.99.8

**Comment by LMF2023** [comment]
请问，Ubuntu中如何安装geph？
Excuse me, how to install geph in Ubuntu?

**Comment by AnyWAT** [comment]
![image](https://github.com/user-attachments/assets/73cfa66d-ff6b-42f7-a7cd-c4d60a114165)
