### ISSUE TITLE
Problem on connection and stability.

### ISSUE THREAD

**Issue by ShirotokiKaze** [geph-official/geph4-client#186]
I updated geph to 4.99 and during my connection I found out that every time I opened a website that requires vpn,on the Geph would show '[Warn] Captured an unknwonTransport'...
This happens after I cleaned my registry using ccleaner to fix my problem on my nic. I had fixed dll problem and clean only one registry that is relevant to VMWare...
After that I tried so many times,only in 1/4 of them did Geph work.There was even only one time that Geph worked during my several tries last night....
Hope u could help me with my problems...
For some unknown reason I cannot even export my dubug pack...so maybe I cannot provide u more information technically...

**Comment by ShirotokiKaze** [comment]
Here is my Geph set up.
![image](https://github.com/user-attachments/assets/30b5669d-beba-431e-ab49-a7135ea65681)
![image](https://github.com/user-attachments/assets/fe781227-1210-43fc-a9a3-7fb01fec2ba4)
![image](https://github.com/user-attachments/assets/bb64a1ce-24f3-446b-9db4-f7f8e7d621b9)

**Comment by AnyWAT** [comment]
试试不用VPN，也不开启“自动配置代理”，浏览器采用代理扩展控制？

**Comment by ShirotokiKaze** [comment]
> 试试不用VPN，也不开启“自动配置代理”，浏览器采用代理扩展控制？ Try not using a VPN or turning on "auto-configuration proxy", but use proxy extension control for the browser?

我windows代理那一栏是关闭的，如下图：
![image](https://github.com/user-attachments/assets/30e6cb09-dd22-4641-9623-022598772adf)
代理扩展控制是我没听说过的概念，能否更详细介绍一下呢
至于V5，我记得应该是没有客户端模式的？之前4.10版本时我的geph出过问题，我试过下载4代的master文件并用rust使用它，但收效甚微

**Comment by AnyWAT** [comment]
一般：不用VPN，不开启系统代理，需要代理的应用尽量在其内部设置代理，如浏览器采用代理扩展控制。此刻可以同时运行N个端口不同的代理软件。
代理扩展：https://github.com/FelisCatus/SwitchyOmega/issues/2513#issuecomment-2218665232
V5有图形与命令行2种模式：https://hackmd.io/@RVd35hG7TziAIk-XA24QLA/r1XjIdbWA

**Comment by ShirotokiKaze** [comment]
我还是觉得geph的客户端好使用一些，只是我想求助到底是哪里出现了问题。。

**Comment by AnyWAT** [comment]
那就在迷雾通里开启“自动配置代理”——实质：开启系统代理

**Comment by ShirotokiKaze** [comment]
> 敝人码盲，但熟悉代理使用。不过一般几乎没人回复你的。。。 那就在迷雾通里开启“自动配置代理”——实质：开启系统代理

我纯小白一个，之前4.10出问题发邮件还有人回复，现在只有机器人。。不得已才在这里求助的
您的方法我会去尝试的，能看到回复我就很开心了

**Comment by ShirotokiKaze** [comment]
因为在修改我的电脑的注册表内容之前我并未使用过4.99的版本，所以现在根本不知道是电脑的问题还是版本的问题T^T

**Comment by AnyWAT** [comment]
WIN10x64 PRO 很好，V4.99.2、V5都正常：非VPN、非系统代理的代理模式

**Comment by ShirotokiKaze** [comment]
> WIN10x64 PRO 很好，V4.99.2、V5都正常：非VPN、非系统代理的代理模式
> 
> > 可以先尝试以管理员身份打开命令提示符，输入以下指令：
> > Dism /Online /Cleanup-Image /CheckHealth
> > Dism /Online /Cleanup-Image /ScanHealth
> > Dism /Online /Cleanup-Image /RestoreHealth
> > sfc /scannow
> > 扫描后重启电脑查看是否能正常运行。

已经在扫描了，我觉得大概率是系统问题了。这两天网卡也是频繁掉，现在只能用手机usb共享热点

**Comment by AnyWAT** [comment]
官方论坛：https://community.geph.io/

**Comment by ShirotokiKaze** [comment]
> 官方论坛：https://community.geph.io/ V5在线：https://discord.com/channels/784822842285490237/1224362564314599535 据说：V4.99.2是套着V4.10.1的皮的V5

对的，作者在geph的推送里有说4.99是V5的core

**Comment by ShirotokiKaze** [comment]
> WIN10x64 PRO 很好，V4.99.2、V5都正常：非VPN、非系统代理的代理模式
> 
> > 可以先尝试以管理员身份打开命令提示符，输入以下指令：
> > Dism /Online /Cleanup-Image /CheckHealth
> > Dism /Online /Cleanup-Image /ScanHealth
> > Dism /Online /Cleanup-Image /RestoreHealth
> > sfc /scannow
> > 扫描后重启电脑查看是否能正常运行。
> 
> > 代理扩展控制是我没听说过的概念，能否更详细介绍一下呢
> 
> 自己谷歌就好。。。

这样扫描之后我的wifi也回来了！
然后用wifi使用geph，不管是自动代理还是全局vpn都能正常使用
后面几天我会保持测试的，谢谢您的帮助！^^

**Comment by AnyWAT** [comment]
官网已从V4.99.2更新到V4.99.8
