### ISSUE TITLE
Why passwords is not encrypted?

### ISSUE THREAD

**Issue by alr86** [geph-official/geph4-client#187]
![Screenshot_۲۰۲۴۰۹۱۸-۲۳۱۳۵۳_URLCheck.png](https://github.com/user-attachments/assets/2a1bd4ec-02c6-4871-843b-b6c07d38bccd)

Why PWD is in URL without any encryption?

**Comment by AnyWAT** [comment]
V5程序配置文件 config.yaml 包含账户、密码明文，还有 username 与 password 文件也是，V4.99.2只是有着V4用户界面下的V5。。。Why PWD is in URL with any encryption?

**Comment by AnyWAT** [comment]
为什么PWD在URL中需要任何加密？

**Comment by alr86** [comment]
为什么这些数据没有被加密，这可能会对许多人的隐私造成威胁，因为他们的所有程序密码都是相同的。

这意味着，如果这些信息以明文形式传输，黑客或恶意用户可能会轻易获取这些敏感信息，从而导致账户被盗或其他安全问题。因此，确保数据的安全性和隐私保护是非常重要的。

**Comment by AnyWAT** [comment]
谷歌市场更新日期：2024年9月18日
