### ISSUE TITLE
plus 版本有流量限制吗

### ISSUE THREAD

**Issue by zuoganggit** [geph-official/geph4-client#189]
plus 版本有流量限制吗

**Comment by fmatrixch** [comment]
官方说没有，不过开了plus之后，欧盟节点依然很慢。

**Comment by AnyWAT** [comment]
传：V4微势，V5威武。
https://community.geph.io/t/topic/16161

**Comment by nullchinchilla** [comment]
一般是限制400MB左右，但根据服务器的资源我有时会随时改。
