### ISSUE TITLE
windows升级4.99后加载不出服务器列表

### ISSUE THREAD

**Issue by justicecancer** [geph-official/geph4-client#190]
一直显示正在加载，可以切公告，论坛，但是选不了服务器节点

**Comment by justicecancer** [comment]
首页也加载不出来

**Comment by justicecancer** [comment]
退出之后：
![image](https://github.com/user-attachments/assets/3aca1efd-f915-41fd-8a31-e1cafcfcb04c)

**Comment by AnyWAT** [comment]
几分钟前已恢复。

**Comment by AnyWAT** [comment]
官网已从V4.99.2更新到V4.99.8
