### ISSUE TITLE
Database error.

### ISSUE THREAD

**Issue by hniksoleimani** [geph-official/geph4-client#191]
![Screenshot from 2024-09-24 11-51-50](https://github.com/user-attachments/assets/d62d6d36-8619-40e8-b114-a9362056b73f)

**Comment by AnyWAT** [comment]
貌似V4.99.8运行在命令行模式？
传说V4.99是披着V4的皮的V5，应该不再支持V4.10.1的命令行运行方式。
V5的命令行模式反而比V4简单多了。
![image](https://github.com/user-attachments/assets/19b23a1b-7de0-4b3e-800a-a007a9d5bb39)

**Comment by dvd73** [comment]
Please fix it asap. @
![2024-10-11 11_17_02-geph5_binaries_geph5-client_src_database rs at 4b3e3a33a1f479eccf9ba7fb6dcc0d4fa](https://github.com/user-attachments/assets/8dff3c97-c6cb-4845-8d82-eda1539d4b05)

System: MX-19.4, Debian 10.13

**Comment by AnyWAT** [comment]
2024/10/17 官网已有WIN版（非默认、手动指定下载）、安卓。。。V4.99.9

**Comment by dvd73** [comment]
> 2024/10/17 官网已有WIN版（非默认、手动指定下载）、安卓。。。V4.99.9

Fixed, thanks a lot
