### ISSUE TITLE
建议加入自定义规则功能

### ISSUE THREAD

**Issue by fmatrixch** [geph-official/geph4-client#192]
市面上大部分的翻墙软件，包括v2ray、Clash等的客户端，均有自定义规则的功能，以允许用户选择自己喜好经过代理和排除代理的网站流量。而迷雾通至今只有一个exclude PRC traffic的功能，该功能并不完善，像是Apple CDN、Bing之类的网站由于存在中国大陆服务器也会被系统默认绕过，导致无法使用特定的AI工具等。

希望开发团队加入自定义规则功能或将部分含有中国特供服务的国外网站设定为强制经过代理服务器

**Comment by AnyWAT** [comment]
浏览器代理扩展，可自定义的自动切换情景模式。。。
V4最后版本V4.10.1
过渡版本V4.99.8（V4的外壳，V5的内核）
最新V5。。。

**Comment by AnyWAT** [comment]
> v2ray、Clash

如果说它们是没有自己飞机的航运公司，那迷雾通则是拥有自己飞机的航运？

**Comment by fmatrixch** [comment]
> > v2ray、Clash
> 
> 如果说它们是没有自己飞机的航运公司，那迷雾通则是拥有自己飞机的航运？

个人认为Geph介于工具和傻瓜式之间。Geph不会很智能地设置系统代理，这点和自由门是不一样的。

**Comment by AnyWAT** [comment]
比较一下迷雾通的“自动配置代理”与赛风运行后自动设置的系统代理，一个简单一个。。。
