### ISSUE TITLE
自建迷雾通连接报错

### ISSUE THREAD

**Issue by gdlwolf** [geph-official/geph4-client#193]
报错内容如下：
[geph4client INFO]: geph4-client v4.99.8 starting...
[geph4client::connect INFO]: connect mode starting: exit = None, force_protocol = None, use_bridges = false
thread 'main' panicked at src\connect\tunnel.rs:53:18:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by AnyWAT** [comment]
官网V4.99.9发布中。。。

**Comment by gdlwolf** [comment]
![image](https://github.com/user-attachments/assets/d06d657a-2bf2-4491-b56d-7e0a4aa9d2c8)
v4.99.9真的会处理吗？

**Comment by AnyWAT** [comment]
码盲不知道呢，只陈述所见所闻而已。大佬时常在此：https://discord.com/channels/784822842285490237/1224362564314599535

**Comment by nullchinchilla** [comment]
自建的话我建议直接用geph5，目前geph4-client变成了套geph5-client的一个非常薄的一个壳
