### ISSUE TITLE
How to update with Cargo 

### ISSUE THREAD

**Issue by dvd73** [geph-official/geph4-client#194]
Hi

Is it possible to update local sources with 

cargo install gepth4-client

**Comment by AnyWAT** [comment]
？https://lib.rs/crates/geph4-client/versions

**Comment by dvd73** [comment]
> ？https://lib.rs/crates/geph4-client/versions

Is it possible to run update as follow ?
`cargo update geph4-client`

Sorry, I'm not a rust developer. My goal is to eliminate the source building each *cargo install* time. My netbook is too slow for this.

Thanks.

**Comment by AnyWAT** [comment]
1、
![image](https://github.com/user-attachments/assets/30ab909b-f22a-44ff-8912-4f29c4875648)

2、
![捕获](https://github.com/user-attachments/assets/11f6e409-c625-48b8-8a02-37d08e0b6de4)

3、
cargo install geph4-client@4.99.10
。。。。。。

**Comment by AnyWAT** [comment]
我是WIN用户，码盲。。。

**Comment by nullchinchilla** [comment]
`cargo install geph4-client --locked` should work since geph4-client is published on crates.io
