### ISSUE TITLE
New executable getting flagged by Windows Defender

### ISSUE THREAD

**Issue by CallMeGary123** [geph-official/geph4-client#195]
Version 4.99.16 gets flagged by windows defender on launch

![image](https://github.com/user-attachments/assets/4a35e363-ac5d-4073-b66c-7598630f2dcb)

**Comment by AnyWAT** [comment]
试试安装到非系统盘？

**Comment by CallMeGary123** [comment]
> 试试安装到非系统盘？ Try installing it on a non-system disk?

I tried that it still flags it

![image](https://github.com/user-attachments/assets/5767639e-6018-4299-8605-84fc62a0d564)

**Comment by AnyWAT** [comment]
手动更新病毒库后再试？

**Comment by CallMeGary123** [comment]
**Some more information** this has started happening since the latest security intelligence update 

Version: 1.421.152.0
Engine Version: 1.1.24090.11
Platform Version: 4.18.24090.11
Released: 11/7/2024 9:52:17 AM

you can read Microsoft's change log [here](https://www.microsoft.com/en-us/wdsi/definitions/antimalware-definition-release-notes) 

**Also** I tried Geph v4.99.14, this version gets flagged too now
![image](https://github.com/user-attachments/assets/b1e967f5-26dd-47fc-8316-b4734b5a6ad3)

**Comment by CallMeGary123** [comment]
> 手动更新病毒库后再试？ Manually update the virus database and try again?

DB is up to date and this started happening since the latest update to the antivirus database

**Comment by AnyWAT** [comment]
我这里，病毒库最新，没有问题。试试运行其它代理软件后再次下载？
![image](https://github.com/user-attachments/assets/4895fd8c-d41c-4661-846e-dc77d9b59a71)

**Comment by CallMeGary123** [comment]
> 我这里，病毒库最新，没有问题。试试运行其它代理软件后再次下载？ I'm here, the virus database is up to date, no problem. Try running a different agent and download it again? ![image](https://private-user-images.githubusercontent.com/37962734/383965529-4895fd8c-d41c-4661-846e-dc77d9b59a71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODQyNjMsIm5iZiI6MTczMDk4Mzk2MywicGF0aCI6Ii8zNzk2MjczNC8zODM5NjU1MjktNDg5NWZkOGMtZDQxYy00NjYxLTg0NmUtZGM3N2Q5YjU5YTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDEyNTI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2OWYxMzczZDM3Zjg3YTg0NDM5ZjBmZWE5OTlkNzA5NmZkZGJjM2U4YzhhMDc1MGM5ODkxNjIyNzNkM2M2YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x9uMGAqRCqqBce8-_-XP_snKpVEIya0OVTCRdp4dJy0)

other proxy agents are fine, i have also tried uninstalling and re-installing.
I think it's a problem with Windows defender **I'll wait for the next update from Microsoft and then I'll post an update here**

**Comment by CallMeGary123** [comment]
the issue persists on the new antivirus DB update
Version: 1.421.156.0
Engine Version: 1.1.24090.11
Platform Version: 4.18.24090.11
Released: 11/7/2024 12:55:44 PM
Documentation: [Release notes](https://www.microsoft.com/en-us/wdsi/definitions/antimalware-definition-release-notes?requestVersion=1.421.156.0)

for now i've just excluded the geph install directory from Windows Defender
if you have the same problem as me here's how to [Add an exclusion to Windows Security](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26)

**Comment by CallMeGary123** [comment]
> This is a false positive; there is of course no virus in the program.
> 
> I reported a false positive to Microsoft and they hopefully will fix this. Currently, if you build it yourself you'll get the same report from Windows Defender.
> 
> I'm also attempting to try other build configurations, etc, to see whether that'll fix this issue.

I also submitted a false positive report earlier today, I'll post an update here if they reply

**Comment by nullchinchilla** [comment]
This *should* be fixed now.

**Comment by AnyWAT** [comment]
> https://www.virustotal.com/gui/file/0d8cf8b00549e35ad5e78c46b748f16e67ed12b36f7add069238babe56f45272?nocache=1

没明白，geph4-client.exe 安装后大小19.3 MB (20,299,264 字节)，检测 geph4-client.exe (copy) 10.61 MB
