### ISSUE TITLE
A strange issue

### ISSUE THREAD

**Issue by omixyy** [geph-official/geph4-client#199]
Something is definetly wrong with the latest version 4.99.17.
It shows that im connected to Amsterdam server, but if I check my location, it shows me at my country at my city. But still it seems like Geph is running
![image](https://github.com/user-attachments/assets/67cefee8-2ddd-4df5-b064-20d310aa9a30)
How do I fix it?

**Comment by AnyWAT** [comment]
Change
Routing Mode：Auto
To：Bridges

**Comment by omixyy** [comment]
Nothing changed, still doesn't work.
![image](https://github.com/user-attachments/assets/565fc55f-7e00-4f40-94d7-cc03cd5d6bba)

**Comment by omixyy** [comment]
Oh it started working after some time, thank you very much

**Comment by TeleportForward** [comment]
looking for GTA5 player for apartment mission mastermind and doomsday hard difficulty，my socialclub user name is FROMathinkYoullD
with battleye on normally Play
