### ISSUE TITLE
使用gephgui4打开后白屏

### ISSUE THREAD

**Issue by 877172750** [geph-official/geph4-client#46]
这个问题怎么处理呢，
![微信图片_20220613171043](https://user-images.githubusercontent.com/107399154/173320615-ed23e10c-7b1e-4666-8bde-8b7ae9afd137.png)
![微信图片_20220613171122](https://user-images.githubusercontent.com/107399154/173320621-bd0abe4b-6f00-4886-9b36-d292f77b04b8.png)

**Comment by 877172750** [comment]
卸载重新安装也没有用

**Comment by sherpk** [comment]
我用的是Mac版本的，也是出现白屏，
<img width="409" alt="image" src="https://user-images.githubusercontent.com/43440970/204215646-56e8285f-04dc-41e9-b741-7eb074a545f5.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/43440970/204215829-d8d69724-0c10-4042-8212-89a01a7aa698.png">
