### ISSUE TITLE
目前迷雾通的所有节点都有高延迟、高丢包率的问题，且连接经常断线，流量分流也不起作用，版本更新后经常出现无法登录的情况，希望这些问题尽快解决，谢谢！

### ISSUE THREAD

**Issue by ghost** [geph-official/geph4-client#55]

**Comment by DaisySunchaser** [comment]
![image](https://user-images.githubusercontent.com/92924434/215754291-df29ea3e-d690-4b25-9bc1-2fc145181d2a.png)
是这样的，今天他无法连接我就登出了，然后更新了版本，就一直无法登录，每次显示错误的原因也不一样。这种情况一般过一段时间再试是否就可以了？
