### ISSUE TITLE
linux端需要直接解压缩运行的版本,flatpak没环境

### ISSUE THREAD

**Issue by kerojiang** [geph-official/geph4-client#57]
之前的tar.xz挺好的，直接解压缩运行就可以了，希望继续提供这个包，或者能否提供编译脚本我自己处理

**Comment by issu-shooter** [comment]
迷雾通本来就可以自己编译，另外flatpak这个包是完全可以安装的。没有flatpak就先用自己发行版的源安装flatpak，然后再把迷雾通的flatpak包名字改成x.y.z的格式，就可以flatpak install x.y.z了
