### ISSUE TITLE
Artix Linux安装Geph-4.6.2.flatpak提示org.gnome.Platform已不再支持，且一直安装失败

### ISSUE THREAD

**Issue by vvvvvx** [geph-official/geph4-client#59]
下载flatpak需要的运行环境总是超时失败，连续几天都无法安装。希望提供appimage包。

$ flatpak install Geph-x86_64.flatpak 

请注意 

'/var/lib/flatpak/exports/share'
'/home/user/.local/share/flatpak/exports/share'

目录不在由 XDG_DATA_DIRS 环境变量设置的搜索路径中，因此通过 Flatpak
安装的应用在会话重启前可能不会出现在您的桌面。

在远程仓库 flathub 中找到 io.geph.GephGui/x86_64/master（runtime/org.gnome.Platform/x86_64/41）需要的运行时
您想要安装它吗？ [Y/n]: 

Info: runtime org.gnome.Platform branch 41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
        ID                                              分支               操作             远程                        下载
 1. [✗] org.freedesktop.Platform.GL.default             21.08              i                flathub                     965.2 kB / 129.8 MB
 2. [✗] org.gnome.Platform.Locale                       41                 i                flathub                       9.1 MB / 337.1 MB
 3. [/] org.gnome.Platform                              41                 i                flathub                     648.2 kB / 292.7 MB
 4. [ ] io.geph.GephGui                                 master             i                gephgui22-origin            0 字节

Warning: 从远程仓库 flathub 提取 runtime/org.freedesktop.Platform.GL.default/x86_64/21.08 时：While fetching https://dl.flathub.org/repo/objects/21/f678223db43c8f62a508e0b38c9f3f4f492f0e6fffc7ecdf33c62dbe893235.filez: [56] Failure when receiving data from the peer
Warning: 从远程仓库 flathub 提取 runtime/org.gnome.Platform.Locale/x86_64/41 时：While fetching https://dl.flathub.org/repo/objects/e5/51789e6c79d8d65cab449c0ce53f3475aff1ed4969df845f7ea583107c3064.filez: [56] Failure when receiving data from the peer
正在安装 3/4… ▍                      2%  12.0 kB/s  44:06

**Comment by chrisqin** [comment]
感觉你这个单纯就是网络问题下不下来。
