### ISSUE TITLE
Android 6.0 (EMUI 4) 安装4.6.2版本无法正常使用

### ISSUE THREAD

**Issue by Ender-003** [geph-official/geph4-client#60]
具体表现为: 点击"连接"按钮后无任何反应, 如图 (1. 点击前; 2. 点击后)

![1](https://user-images.githubusercontent.com/67150107/204313087-47353955-09b5-4016-892e-9cb1cfcdb6a5.png)

![2](https://user-images.githubusercontent.com/67150107/204313043-d5677106-bacb-4633-a456-98e1fd524069.png)

**Comment by maidxiaoling** [comment]
我三星的，安卓6，同样问题。
