### ISSUE TITLE
flathub 无法连接

### ISSUE THREAD

**Issue by randoruf** [geph-official/geph4-client#69]
希望能够提供 Linux 环境下直接运行的二进制文件。因为无法连接到 flathub

**Comment by justin-himself** [comment]
赞同. flathub 就是一坨冷透了的屎

**Comment by i39v** [comment]
试试[这个](https://github.com/geph-official/gephgui-pkg/tree/master/blobs/linux-x64)

**Comment by randoruf** [comment]
@i39v 感谢
