### ISSUE TITLE
是否支持后量子算法？

### ISSUE THREAD

**Issue by oilel** [geph-official/geph4-client#72]
[https://csrc.nist.gov/projects/post-quantum-cryptography/selected-algorithms-2022](https://csrc.nist.gov/projects/post-quantum-cryptography/selected-algorithms-2022)

**Comment by nullchinchilla** [comment]
会考虑将来在sosistab2中加入。不过目前还不在日程（我个人不是特别看好量子计算的发展

**Comment by oilel** [comment]
> 会考虑将来在sosistab2中加入。

但是有一个问题要注意：就是AES-256和ChaCha20在量子计算机面前只有128位安全性，**_但是_**后量子算法Kyber、McEliece都能提供256位安全性，导致**_安全性有短板_**。因此建议这样：如果NIST尚未更新对称加密算法，就直接用Kyber进行**_双向通信_**，通信全程都不采用对称加密，这样就有256位安全性了。

**Comment by oilel** [comment]
Sorry, it seems to be my fault. It seems that Kyber1024 provides the same security as AES256. 也就是说，如果我真的搞错了Kyber的安全性，就不用在双向通信都采用Kyber了。但是目前不确定Kyber1024到底是提供128位还是256位安全性，所以我说 seems to be 然后才 my fault 。 @nullchinchilla

**Comment by oilel** [comment]
https://www.ambit.inc/pdf/KyberDrive.pdf @nullchinchilla As this research said: "Kyber-1024 is known to have 254 bits of classical security and 230 bits of quantum security (coreSVP hardness)." 也就是说，Kyber1024的安全性远超AES。256位AES对量子计算机的安全性至多128位，然而Kyber1024提供230位安全性。因此建议使用三重AES（模仿3DES），因为3DES就是用了三重DES才达到112位安全性。因为中途相遇攻击（meet-in-the-middle-attack），所以三重的256位AES才达到256位的后量子安全性。只能临时模仿一下三重DES了。
