### ISSUE TITLE
win11无法连接账户信息，卡死闪退

### ISSUE THREAD

**Issue by 12345678909876543** [geph-official/geph4-client#77]
切换到设置界面就无法下拉，我无法导出调试信息
![QQ截图20230105103816](https://user-images.githubusercontent.com/110444905/210689698-433651db-c372-4457-b7f2-7fd6a2e8b83d.png)
![QQ截图20230105104118](https://user-images.githubusercontent.com/110444905/210689708-8be9ecd8-9ea4-4b61-93ad-61e148ad5be1.png)

**Comment by AnyWAT** [comment]
退出迷雾通，其安装目录下的 MicrosoftEdgeWebview2Setup.exe 更新一下 WebView 或许就好了

**Comment by 12345678909876543** [comment]
> 退出迷雾通，其安装目录下的 MicrosoftEdgeWebview2Setup.exe 更新一下 WebView 或许就好了

好的 非常感谢
