### ISSUE TITLE
geph4-client连接时报错，跪求大佬指教中...

### ISSUE THREAD

**Issue by hanshoukai** [geph-official/geph4-client#82]
具体的报错信息如下：
hankai@HandeMBP ~ % geph4-client connect --override-connect  7631c7f4e623602ba1facedb84356b9e88ee91xxxxx68944b68429001766537879@158.247.220.13:17814

[geph4client INFO]: geph4-client v4.7.1 starting...
[geph4client::connect INFO]: connect mode starting: exit = None, force_protocol = None, use_bridges = false
[geph4client::connect::vpn INFO]: not starting VPN mode
     [geph4client::connect DEBG]: gonna construct the tunnel
[geph4client::connect::socks5 DEBG]: socks5 started
   [geph4client::connect::dns DEBG]: DNS loop started
thread 'sscale-wkr-c' panicked at 'not yet implemented', /Users/hankai/.cargo/registry/src/github.com-1ecc6299db9ec823/geph4-client-4.7.1/src/connect/tunnel/getsess.rs:41:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[geph4client::connect::socks5 DEBG]: gonna use the tunnel now
[geph4client::connect::socks5 DEBG]: socks5 died with: sending into a closed channel
[geph4client::connect::socks5 DEBG]: gonna use the tunnel now
[geph4client::connect::socks5 DEBG]: socks5 died with: sending into a closed channel
[geph4client::connect::socks5 DEBG]: gonna use the tunnel now
[geph4client::connect::socks5 DEBG]: socks5 died with: sending into a closed channel
[geph4client::connect::socks5 DEBG]: gonna use the tunnel now
[geph4client::connect::socks5 DEBG]: socks5 died with: sending into a closed channel
[geph4client::connect::socks5 DEBG]: gonna use the tunnel now

**Comment by nullchinchilla** [comment]
请更新geph4-client
