### ISSUE TITLE
[macOS] version numbers broken in recent releases

### ISSUE THREAD

**Issue by core-code** [geph-official/geph4-client#86]
i've downloaded version 4.7.3 but it claims to be version 4.5:

<img width="689" alt="Screenshot 2023-01-26 at 12 35 16" src="https://user-images.githubusercontent.com/1261954/214826035-27fc5251-70e6-4d77-9344-baff873e174d.png">
<img width="505" alt="Screenshot 2023-01-26 at 12 35 13" src="https://user-images.githubusercontent.com/1261954/214826045-13374284-9307-4b71-9527-9d0f74f6140f.png">
<img width="261" alt="Screenshot 2023-01-26 at 12 35 05" src="https://user-images.githubusercontent.com/1261954/214826046-1cad2842-4d79-4243-b395-011819f9ab95.png">

the `CFBundleVersion` and `CFBundleShortVersionString` entries in your `Info.plist` file are broken

**Comment by nullchinchilla** [comment]
Ah, I haven't noticed this place! Thanks for the headsup, will fix next version.

**Comment by core-code** [comment]
awesome, thanks!

**Comment by core-code** [comment]
still broken in 4.7.5

**Comment by core-code** [comment]
still broken in 4.7.6

**Comment by core-code** [comment]
no improvements in 4.7.7 either

**Comment by core-code** [comment]
still broken in '4.7.10'

**Comment by suschizu** [comment]
version numbers still display 4.5 in release 4.7.12 …
