### ISSUE TITLE
新版请不要丢下win7用户

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [geph-official/geph4-client#91]
v4.6以需要win10 edge webview runtime所以win7用户无法安装

**Comment by CT-ABT** [comment]
是的，我家人也有反应说无法运行在 1809 LTSC 上。按理说 Edge WebView 应该不是问题，因此似乎是程序自身在检测系统版本上有所强制。

**Comment by piiiiiiiiiiiiiii** [comment]
day day up

**Comment by youngbais** [comment]
到这里 https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section 或者https://go.microsoft.com/fwlink/p/?LinkId=2124703 下载Microsoft Edge WebView2安装程序.运行后会自动下载适用于Windows 7系统的 109.0.1518.78 WebView2版本.再打开geph最新版本就不会闪退了.
![QQ截图20230320130417](https://user-images.githubusercontent.com/7010890/226251301-b3f252b9-115c-4d52-914d-c90ea03400b9.png)

**Comment by youngbais** [comment]
> v4.6以需要win10 edge webview runtime所以win7用户无法安装

试试我上面回复的.

**Comment by CT-ABT** [comment]
> 到这里 https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section 或者https://go.microsoft.com/fwlink/p/?LinkId=2124703 下载Microsoft Edge WebView2安装程序.运行后会自动下载和安装适用于Windows 7系统的WebView2 109.0.1518.78 版本.再打开geph最新版本就不会闪退了. ![QQ截图20230320130417](https://user-images.githubusercontent.com/7010890/226251301-b3f252b9-115c-4d52-914d-c90ea03400b9.png)

不是闪退问题，是之前据反映 4.6.3 时是安装程式直接报告不支援 Windows 10 1803 以下的版本，现在应该是修复了。

**Comment by youngbais** [comment]
> > 到这里 https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section 或者https://go.microsoft.com/fwlink/p/?LinkId=2124703 下载Microsoft Edge WebView2安装程序.运行后会自动下载和安装适用于Windows 7系统的WebView2 109.0.1518.78 版本.再打开geph最新版本就不会闪退了. ![QQ截图20230320130417](https://user-images.githubusercontent.com/7010890/226251301-b3f252b9-115c-4d52-914d-c90ea03400b9.png)
> 
> 不是闪退问题，是之前据反映 4.6.3 时是安装程式直接报告不支援 Windows 10 1803 以下的版本，现在应该是修复了。

新版本geph安装完会自动安装自带的Microsoft Edge WebView2 runtime.但是Windows 7不支持自带的那个版本.所以会提示安装失败.需要在Windows 10中安装使用.没有安装WebView2 runtime的系统打开geph客户端就会闪一下就没了.

**Comment by CT-ABT** [comment]
> > > 到这里 https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section 或者https://go.microsoft.com/fwlink/p/?LinkId=2124703 下载Microsoft Edge WebView2安装程序.运行后会自动下载和安装适用于Windows 7系统的WebView2 109.0.1518.78 版本.再打开geph最新版本就不会闪退了. ![QQ截图20230320130417](https://user-images.githubusercontent.com/7010890/226251301-b3f252b9-115c-4d52-914d-c90ea03400b9.png)
> > 
> > 
> > 不是闪退问题，是之前据反映 4.6.3 时是安装程式直接报告不支援 Windows 10 1803 以下的版本，现在应该是修复了。
> 
> 新版本geph安装完会自动安装自带的Microsoft Edge WebView2 runtime.但是Windows 7不支持自带的那个版本.所以会提示安装失败.需要在Windows 10中安装使用.没有安装WebView2 runtime的系统打开geph客户端就会闪一下就没了.

我觉得您跟我犟这个真是没有必要。这个事情是我完整经历过的，我在国内的家人用的是 Windows 10 1809 LTSC, 结果被告知无法安装。说明至少早期 4.6 以上的版本被人为写入了检查 Windows 版本是否在 1903 以上的这样一个判断。

我也说了，后来这个问题已经不存在了，因为家人还在用 1809 LTSC, 但已经可以装了。至于 WebView, 没装的会自动检测并安装，这个在其他没有 WebView 的系统上（比如 Windows Server）也是一样的，我并没有否定它不会自行检测安装，仅仅是指出早期版本不知道为什么加入了一个检测是否是 Windows 10 1903 以下版本的怪异判断而已。

**Comment by youngbais** [comment]
> > > > 到这里 https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section 或者https://go.microsoft.com/fwlink/p/?LinkId=2124703 下载Microsoft Edge WebView2安装程序.运行后会自动下载和安装适用于Windows 7系统的WebView2 109.0.1518.78 版本.再打开geph最新版本就不会闪退了. ![QQ截图20230320130417](https://user-images.githubusercontent.com/7010890/226251301-b3f252b9-115c-4d52-914d-c90ea03400b9.png)
> > > 
> > > 
> > > 不是闪退问题，是之前据反映 4.6.3 时是安装程式直接报告不支援 Windows 10 1803 以下的版本，现在应该是修复了。
> > 
> > 
> > 新版本geph安装完会自动安装自带的Microsoft Edge WebView2 runtime.但是Windows 7不支持自带的那个版本.所以会提示安装失败.需要在Windows 10中安装使用.没有安装WebView2 runtime的系统打开geph客户端就会闪一下就没了.
> 
> 我觉得您跟我犟这个真是没有必要。这个事情是我完整经历过的，我在国内的家人用的是 Windows 10 1809 LTSC, 结果被告知无法安装。说明至少早期 4.6 以上的版本被人为写入了检查 Windows 版本是否在 1903 以上的这样一个判断。
> 
> 我也说了，后来这个问题已经不存在了，因为家人还在用 1809 LTSC, 但已经可以装了。至于 WebView, 没装的会自动检测并安装，这个在其他没有 WebView 的系统上（比如 Windows Server）也是一样的，我并没有否定它不会自行检测安装，仅仅是指出早期版本不知道为什么加入了一个检测是否是 Windows 10 1903 以下版本的怪异判断而已。

不知道你是不是看不见issue的标题写的是什么?是你在跟我犟才对吧?我从始至终都没说Windows 10上使用有什么问题.我只是在给楼主提供一个Windows 7上使用不了的解决方法.请问是你理解能力有问题.还是我的表述的不清楚?

**Comment by CT-ABT** [comment]
> > > > > 到这里 https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section 或者https://go.microsoft.com/fwlink/p/?LinkId=2124703 下载Microsoft Edge WebView2安装程序.运行后会自动下载和安装适用于Windows 7系统的WebView2 109.0.1518.78 版本.再打开geph最新版本就不会闪退了. ![QQ截图20230320130417](https://user-images.githubusercontent.com/7010890/226251301-b3f252b9-115c-4d52-914d-c90ea03400b9.png)
> > > > 
> > > > 
> > > > 不是闪退问题，是之前据反映 4.6.3 时是安装程式直接报告不支援 Windows 10 1803 以下的版本，现在应该是修复了。
> > > 
> > > 
> > > 新版本geph安装完会自动安装自带的Microsoft Edge WebView2 runtime.但是Windows 7不支持自带的那个版本.所以会提示安装失败.需要在Windows 10中安装使用.没有安装WebView2 runtime的系统打开geph客户端就会闪一下就没了.
> > 
> > 
> > 我觉得您跟我犟这个真是没有必要。这个事情是我完整经历过的，我在国内的家人用的是 Windows 10 1809 LTSC, 结果被告知无法安装。说明至少早期 4.6 以上的版本被人为写入了检查 Windows 版本是否在 1903 以上的这样一个判断。
> > 我也说了，后来这个问题已经不存在了，因为家人还在用 1809 LTSC, 但已经可以装了。至于 WebView, 没装的会自动检测并安装，这个在其他没有 WebView 的系统上（比如 Windows Server）也是一样的，我并没有否定它不会自行检测安装，仅仅是指出早期版本不知道为什么加入了一个检测是否是 Windows 10 1903 以下版本的怪异判断而已。
> 
> 不知道你是不是看不见issue的标题写的是什么?是你在跟我犟才对吧?我从始至终都没说Windows 10上使用有什么问题.我只是在给楼主提供一个Windows 7上使用不了的解决方法.请问是你理解能力有问题.还是我的表述的不清楚?

我专门开了个虚拟机器试了一下，发现确实 Windows 7 还是不行。我以为它更新后能够自动选择正确的 WebView 版本，结果没想到竟然是自动下载到最后结果安装失败。确实是我错了。

**Comment by piiiiiiiiiiiiiii** [comment]
请开发者支持win7

**Comment by nullchinchilla** [comment]
我自己主要并不熟悉如何让新webview支持旧windows 7，我也日常不用windows，不熟悉windows生态。欢迎给迷雾通安装程序PR： https://github.com/geph-official/gephgui-pkg

**Comment by AnyWAT** [comment]
> 请开发者支持win7

该系统被巨硬废弃N久了，有何必要？
再说。。。见：https://community.geph.io/t/topic/12681

**Comment by piiiiiiiiiiiiiii** [comment]
自己搭了一个，不用迷雾通了
