### ISSUE TITLE
Can't access openai.com via Geph

### ISSUE THREAD

**Issue by mendax1234** [geph-official/geph4-client#92]
l have forced all traffic to use Geph, but l still don't have access to openai. Is there any solution?
<img width="314" alt="image" src="https://user-images.githubusercontent.com/62934294/218243239-2b69852e-4636-404a-8df3-6108ba1fe66a.png">

**Comment by qunge5211314** [comment]
Try changing the operating system's time zone and time to match the location selected in Geph.

**Comment by mendax1234** [comment]
> Try changing the operating system's time zone and time to match the location selected in Geph.

Thanks. That's a good idea. I will try it.
